language: php

dist: xenial

php:
  - 7.2

services:
  - postgresql

env:
  - KONG_DATABASE=postgres KONG_PG_DATABASE=kong KONG_PG_HOST=localhost KONG_PG_PASSWORD=kong KONG_PG_USER=kong KONG_BASE_URL=http://localhost:8001 KONG_DEB_LOCATION=https://bintray.com/kong/kong-community-edition-deb/download_file?file_path=dists/kong-community-edition-1.0.2.xenial.all.deb
  - KONG_DATABASE=postgres KONG_PG_DATABASE=kong KONG_PG_HOST=localhost KONG_PG_PASSWORD=kong KONG_PG_USER=kong KONG_BASE_URL=http://localhost:8001 KONG_DEB_LOCATION=https://bintray.com/kong/kong-community-edition-deb/download_file?file_path=dists/kong-community-edition-0.15.0.xenial.all.deb

before_script:
  - sudo apt install -y libc6

  - wget -O kong.deb $KONG_DEB_LOCATION
  - sudo dpkg -i kong.deb

  - psql -c "CREATE DATABASE kong;" -U postgres
  - psql -c "CREATE USER kong WITH PASSWORD 'kong';" -U postgres

  - sudo kong migrations bootstrap

  - composer self-update
  - composer install --no-interaction
  - sudo kong start

script:
  - composer run ci

after_success:
  - travis_retry php vendor/bin/php-coveralls